version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - dogsled
    - durationcheck
    - gocritic
    - govet
    - misspell
    - unconvert
    - usestdlibvars
  disable:
    - unused
    - ineffassign
    - staticcheck
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
