version: "2"
linters:
  enable:
    - errcheck
    - gosimple
  disable:
    - unused
    - ineffassign
    - staticcheck
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
