# Copyright IBM Corp. 2013, 2025
# SPDX-License-Identifier: MIT

version: "2"
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - dogsled
    - durationcheck
    - govet
    - misspell
    - usestdlibvars
  disable:
    - asasalint
    - errcheck
    - gocritic
    - ineffassign
    - staticcheck
    - unconvert
    - unused
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
